# -*- mode: ruby -*-
# vi: set ft=ruby :

require './variables.rb'

Vagrant.configure("2") do |config|

  config.vm.box = BOX
  
  config.vm.hostname = HOSTNAME
  config.vm.base_address = IPADDR
  config.vm.base_mac = MACADDR
  config.vm.synced_folder ".", "/vagrant"
  
  config.vm.provider PROVIDER do |v|
    v.clone_directory = CLONE_DIRECTORY
    v.gui = GUI
    v.vmx["displayName"] = HOSTNAME
    v.vmx["numvcpus"] = CPU
    v.vmx["memsize"] = MEMORY
  end
  
  config.vm.provision "shell", path: "provision/bootstrap.sh"

end